<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_WhatsApp Number_business_name</name>
   <tag></tag>
   <elementGuidId>81b0429f-caa7-4cb5-8892-bae9ec859566</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='business_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;business_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Business Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d46e972-dfb6-4b94-9b32-e508b6300db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>business_name</value>
      <webElementGuid>e4159338-713b-424f-8ef3-291ebd84225f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8d791587-9423-49c8-8eb8-1e9b3bb96c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>company_name form-control demo-form-control</value>
      <webElementGuid>3c794a8a-a721-4a45-afcd-527b94515c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Business Name</value>
      <webElementGuid>6055a630-21be-48fa-bd2a-9f60ef2950e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swup&quot;)/section[@class=&quot;demo-section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-6&quot;]/div[@class=&quot;demo-form-container&quot;]/div[@class=&quot;from_box&quot;]/div[@class=&quot;form-floating demo-form-group&quot;]/input[@class=&quot;company_name form-control demo-form-control&quot;]</value>
      <webElementGuid>de51d376-eb73-429e-b100-4baa2c250049</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='business_name']</value>
      <webElementGuid>7a170eac-e479-4a31-b05a-00a7fd10211e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='swup']/section/div/div/div/div/div/div[3]/input</value>
      <webElementGuid>8457e9cc-b5a6-42f4-b738-e49ec79cb91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>71e63b67-53b0-4469-9054-d71ee61c2ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'business_name' and @type = 'text' and @placeholder = 'Business Name']</value>
      <webElementGuid>0247ff0d-6be4-4999-b2a2-e0d09db62ae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
