<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Transaction details of Withdrawal for Ac_3414fc</name>
   <tag></tag>
   <elementGuidId>59dd3d94-1799-4121-b8c5-bc1463026488</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#withdraw > tbody > tr > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='withdraw']/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Transaction details of Withdrawal for Account 175238&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>482c0aca-8646-4865-be74-563124703a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>bc2c18d9-57c7-4798-8280-806c5e0b04b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transaction details of Withdrawal for Account 175238</value>
      <webElementGuid>c9ade21c-bde4-4c19-8913-3591b2493485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;withdraw&quot;)/tbody[1]/tr[1]/td[1]</value>
      <webElementGuid>9eeb4383-03d8-40a3-9644-67c443a84bb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='withdraw']/tbody/tr/td</value>
      <webElementGuid>f387ff61-0304-4646-aa6c-4333300def4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::td[2]</value>
      <webElementGuid>4e8ef58e-85a9-4d41-9582-2c64c4d32370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customised Statement'])[1]/following::td[2]</value>
      <webElementGuid>3d13d7b0-0c4e-4a6f-88a3-88175d43ca76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction ID'])[1]/preceding::td[1]</value>
      <webElementGuid>bdace87f-7d70-4f69-b489-f671bce51068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td</value>
      <webElementGuid>f2292b46-d3ab-472c-ad6a-940b27adca0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Transaction details of Withdrawal for Account 175238' or . = 'Transaction details of Withdrawal for Account 175238')]</value>
      <webElementGuid>000ca897-95b1-40c6-b27d-a4c31237e5e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
