<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Remember Me</name>
   <tag></tag>
   <elementGuidId>2b407882-5c39-4381-bc3c-e016f9e67bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.checkbox-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login']/div/div/div/div[3]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Remember Me&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ef400f9d-f055-4fbd-9d8a-9c6f32264e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>rememberchb</value>
      <webElementGuid>c63b3324-1b88-43f3-aaac-fcc24646708e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-label</value>
      <webElementGuid>321b2692-d140-4225-9fc4-7b3d34cb4741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remember Me</value>
      <webElementGuid>2fbf7c53-3ba8-4c74-8396-7b297e5efcc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;card-style mt-5 col-md-5 mx-auto rounded-4&quot;]/div[@class=&quot;content mb-0 p-3 p-md-4 card rounded-4&quot;]/div[@class=&quot;d-flex align-items-center justify-content-between mb-4 form-options&quot;]/div[@class=&quot;custom-checkbox-wrapper mb-0 d-flex align-items-center gap-2&quot;]/label[@class=&quot;checkbox-label&quot;]</value>
      <webElementGuid>338e0408-83dc-4305-9e13-b16157a45496</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/div/div/div/div[3]/div/label</value>
      <webElementGuid>d34d7063-53c3-4196-ab07-8ac9fde2d9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::label[1]</value>
      <webElementGuid>b4ca37f9-6bd5-4bc7-84f7-8d5c79310ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/following::label[2]</value>
      <webElementGuid>d7f926e9-ce51-4a9c-8748-a788e0eac4a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Password'])[1]/preceding::label[1]</value>
      <webElementGuid>fe7bc38b-279b-4cdb-9385-c4d0df5fe2a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[5]/preceding::label[2]</value>
      <webElementGuid>7c553d1b-54e7-4e27-9a80-857db49f657f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remember Me']/parent::*</value>
      <webElementGuid>f2934d8b-d922-4740-990a-94df68a75c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/label</value>
      <webElementGuid>8ecd5a9d-5fdb-4c23-9097-ebb0fa344854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Remember Me' or . = 'Remember Me')]</value>
      <webElementGuid>3d670627-1fa8-4a8e-aefd-8275370ab7dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
