<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Password_checkmark</name>
   <tag></tag>
   <elementGuidId>afc8180d-b067-4e7d-99d3-5a07f0c716f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login']/div/div/div/div[3]/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.checkmark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#login span >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1b368065-7c04-435c-ae63-7bdbba73fcfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>b26b61f4-61bd-4517-a179-9d9ec974384d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;card-style mt-5 col-md-5 mx-auto rounded-4&quot;]/div[@class=&quot;content mb-0 p-3 p-md-4 card rounded-4&quot;]/div[@class=&quot;d-flex align-items-center justify-content-between mb-4 form-options&quot;]/div[@class=&quot;custom-checkbox-wrapper mb-0 d-flex align-items-center gap-2&quot;]/div[@class=&quot;custom-checkbox&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>86a482d3-6dcb-4c5d-ab57-dd6ba5590254</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/div/div/div/div[3]/div/div/span</value>
      <webElementGuid>92161b36-38c1-43af-bad2-4a2466cfb657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span</value>
      <webElementGuid>b13d84d5-8494-46be-b411-19bc704f1728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
