<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Number must not be blank_AccSubmit</name>
   <tag></tag>
   <elementGuidId>411393e8-acdf-4387-9019-9efc02cf7687</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='AccSubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;AccSubmit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00adb64c-323c-4b51-8190-dd4b610e144c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>990441c2-5ff7-47d7-9b32-9f651208b9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccSubmit</value>
      <webElementGuid>f8e3b790-0062-4c22-8a4c-71fc57e313eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>7cfb8511-af62-46b9-8952-c42fbc4e9522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;cb-customize-desktop chrome&quot;]/body[1]/table[@class=&quot;layout&quot;]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[11]/td[2]/input[1]</value>
      <webElementGuid>f91e0f33-115a-426e-8001-05adafe133a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='AccSubmit']</value>
      <webElementGuid>69b67eb3-d1d4-4d56-ba1a-969ea3824d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[2]/input</value>
      <webElementGuid>cddefb0f-fbec-4e42-b5a1-ced35e531547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'AccSubmit']</value>
      <webElementGuid>bb0d5718-a349-472b-acfa-64a17947fb9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
