<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>57f0c827-e29e-43e5-acdd-10758098795f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.px-4.rounded-4.w-100.fw-light.d-flex.justify-content-between.align-items-center.waves-effect > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Flight'])[1]//*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form >> internal:has-text=&quot;JKT Soekarno-Hatta International Airport 09:50 pm 3:0 Direct SIN Singapore Chang&quot;i >> internal:role=button >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>3a95232a-8076-4b63-b4b0-4f7094018dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>cb9239f1-02d4-4a5e-89be-db509c780708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>6caf78a1-9ad9-4c14-b0a8-01c462653154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>6c1a15b7-4907-4527-9a02-88f1c744fb7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>f1045847-4d4b-44fd-9c77-f103f8cb7a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>ec209687-80b4-44b6-b085-ec9ca31fa15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#ffffff</value>
      <webElementGuid>31b5c5a7-c92d-40ae-9dc1-8d7b7c9eee68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>cc5cb415-f967-4b1c-afe1-fb396fd49466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>699a6a59-3fdc-4a73-a7eb-3f7496db4baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>b7a9ac74-2734-4aeb-817e-5f8e8e2c69e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fadein&quot;)/main[1]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;container mb-5 mt-2&quot;]/div[@class=&quot;row g-3&quot;]/div[@id=&quot;flight-list&quot;]/div[@class=&quot;flights-container&quot;]/ul[@id=&quot;flight-list&quot;]/li[@class=&quot;flight-item mix all mb-3 flight_list ng-scope&quot;]/form[@class=&quot;ng-pristine ng-valid&quot;]/div[@class=&quot;card border mt-n1 rounded-4 overflow-hidden&quot;]/div[1]/div[@class=&quot;row g-0&quot;]/div[@class=&quot;col-12 col-md-3 text-start p-3 overflow-hidden bg-light&quot;]/div[@class=&quot;d-flex flex-column justify-content-center h-100&quot;]/div[@class=&quot;text-black fs-5 fw-semibold mb-2&quot;]/div[@class=&quot;d-flex justify-content-start align-items-center gap-2&quot;]/button[@class=&quot;btn btn-primary px-4 rounded-4 w-100 fw-light d-flex justify-content-between align-items-center waves-effect&quot;]/svg[1]</value>
      <webElementGuid>89e6f453-6fad-4aaf-8cb6-5d8bbca382bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Flight'])[1]//*[name()='svg'][1]</value>
      <webElementGuid>2071ab74-8130-4363-8f7b-256469a3df94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[3]/following::*[name()='svg'][1]</value>
      <webElementGuid>a683b5d7-2f4c-440e-9f4c-be91258be93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JKT'])[3]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>4ca185e8-d5b7-4d39-a792-cef18c81c370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soekarno-Hatta International Airport'])[3]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>aeac90c3-e2f9-48ea-98e6-ef89728607bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
