<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Deposit</name>
   <tag></tag>
   <elementGuidId>14a93794-2eb6-47c0-9181-58c207a93e61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.menusubnav > li:nth-of-type(8) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Deposit')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Deposit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>186589e6-595f-4ef1-a7df-a80411d47df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>DepositInput.php</value>
      <webElementGuid>cf8f4f80-fee2-4e86-a5f4-77ae179a12fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deposit</value>
      <webElementGuid>c699caea-20f0-4cec-81e3-8cfe77ce01b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;cb-customize-desktop chrome&quot;]/body[1]/div[3]/div[1]/ul[@class=&quot;menusubnav&quot;]/li[8]/a[1]</value>
      <webElementGuid>a4211bf0-8fdf-4f1d-86f9-350ca2d8f250</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Deposit')]</value>
      <webElementGuid>77edbe6d-0855-4f54-9aaa-73aa19ead449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Account'])[1]/following::a[1]</value>
      <webElementGuid>6f319229-882b-45d8-b23f-29eb139d7be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Account'])[1]/following::a[2]</value>
      <webElementGuid>8d3d6139-40a4-41f9-8e08-dcdda62b5b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Withdrawal'])[1]/preceding::a[1]</value>
      <webElementGuid>0d2c14eb-81ef-4ecf-89d8-700279379c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fund Transfer'])[1]/preceding::a[2]</value>
      <webElementGuid>4ddf0e85-16d4-4244-bf4d-711e9a586327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Deposit']/parent::*</value>
      <webElementGuid>7f18abf9-6843-4058-b351-45095aa6b2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'DepositInput.php')]</value>
      <webElementGuid>8ea0d20c-f0dd-4c97-93d7-894f655c896c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[8]/a</value>
      <webElementGuid>c566fd92-178d-421a-b73f-5bc4dfbc546e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'DepositInput.php' and (text() = 'Deposit' or . = 'Deposit')]</value>
      <webElementGuid>5f8b0ec9-7479-437a-9d3f-67e1c6c03bdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
