<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Flying From_to</name>
   <tag></tag>
   <elementGuidId>0b41aea4-6c4e-4e1c-917b-fb31fc90a6e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;to&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='to']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;to&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20fe044f-5b22-4d03-b259-2fc0139c320d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ct px-md-3 ft</value>
      <webElementGuid>91359c68-17d4-416d-9286-ecd15f5ec3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>to</value>
      <webElementGuid>09732555-4df4-4c9b-bb69-fb50669aca09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>a49dbcc4-2bc7-4049-8278-9f99d4235fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Flying From</value>
      <webElementGuid>d3ea8666-3f24-436d-b151-50cda61c9036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onereturn&quot;)/div[@class=&quot;col-12 col-md-3&quot;]/div[@class=&quot;form-floating flight_search&quot;]/input[@class=&quot;form-control ct px-md-3 ft&quot;]</value>
      <webElementGuid>731909ce-8ae0-474c-9c0c-65de00ac2bc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='to']</value>
      <webElementGuid>95dfc62b-a2b0-41db-8a08-369e46c84f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='onereturn']/div[2]/div[2]/input</value>
      <webElementGuid>932332ca-5fc1-46ee-8648-fad27527f8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>32b2973d-e4b4-4fca-a7e5-404253ea386b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'to' and @type = 'search' and @placeholder = 'Flying From']</value>
      <webElementGuid>1dbcbc37-940a-4cdf-a36f-2da7fbc64f98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
