<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_Indonesia</name>
   <tag></tag>
   <elementGuidId>acd64482-7f85-4cac-a3bc-db9dcce348fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='onereturn']/div/div/div/div[4]/div/strong/small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Indonesia&quot;i >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>a73676ec-2e01-4047-8277-a4b23ec8435d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia</value>
      <webElementGuid>ef4f2bff-d20a-464a-9bf0-3a3d87d56a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onereturn&quot;)/div[@class=&quot;col-12 col-md-3&quot;]/div[@class=&quot;form-floating flight_search&quot;]/div[@class=&quot;most--popular-from fadein results-container-from rounded-2 shadow border-0&quot;]/div[@class=&quot;d-flex align-items-center p-2 to--insert overflow-hidden result-option&quot;]/div[@class=&quot;mx-2&quot;]/strong[1]/small[1]</value>
      <webElementGuid>d7222c49-d707-437f-b822-e3d9dd5434d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='onereturn']/div/div/div/div[4]/div/strong/small</value>
      <webElementGuid>c6dd86f2-1757-4734-ae78-cb72b343158c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CGK'])[1]/following::small[1]</value>
      <webElementGuid>28482cd9-c83c-457a-88f2-81c614ac5fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soekarno-Hatta International Airport'])[1]/preceding::small[1]</value>
      <webElementGuid>de68f729-51ba-49ea-a221-aee5e27a575b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/strong/small</value>
      <webElementGuid>2a34b1b3-7eee-4dbc-9fcc-e90cb5d10b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[(text() = 'Indonesia' or . = 'Indonesia')]</value>
      <webElementGuid>ca446149-215e-4d21-9d1c-4fd3de8d11be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
