<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Infants_c8LPF-icon</name>
   <tag></tag>
   <elementGuidId>132831df-6646-495c-9dad-5445a785cef5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.c8LPF-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Infants'])[1]/following::*[name()='svg'][3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#onereturn #flights-search</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>a2142cc5-e8bd-4db7-b3a6-676c846bebe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>6431aa27-c5a5-45c8-b1f5-521c80ba8b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 200 200</value>
      <webElementGuid>a9155368-009a-4e7c-b22e-a432314148b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c8LPF-icon</value>
      <webElementGuid>2abf09ea-9834-4538-a9b1-c15cf23f8bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>35685e0c-cc0d-4e13-bd75-2aa21a7c42d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>61916775-06ce-48d1-a944-251689a13691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onereturn&quot;)/div[@class=&quot;col-lg-1&quot;]/button[@id=&quot;flights-search&quot;]/svg[@class=&quot;c8LPF-icon&quot;]</value>
      <webElementGuid>2b7c6e7b-81d5-4406-ba8d-8a842b69af18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Infants'])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>c9d720b0-77e0-453c-bc5e-265b1331d3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Childs'])[1]/following::*[name()='svg'][5]</value>
      <webElementGuid>418c0117-bfa4-47ee-bca4-c66156c72d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Featured Flights'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>b5fa97fe-4b30-442d-8dc6-008022cd354a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
